# Change these first
owner: Ching367436 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Ching367436's blog
    url: https://blog.ching367436.me
  - name: BambooFox Main Site
    url: https://bamboofox.cs.nycu.edu.tw
  # My CTF Challenges
  - name: 'CTF: Frontend Unraveling Web Application: Master Obfuscated Code Odyssey'
    url: https://fuwamoco-flag-checker.ching367436.me
  - name: 'CTF: Starburst Cat Shop'
    url: https://starburst-cat-shop.ching367436.me
  - name: 'CTF: Login Panel'
    url: https://login-panel.ching367436.me
  - name: 'CTF: Login Panel 2'
    url: https://login-panel-2.ching367436.me
  - name: 'CTF: Curl Online'
    url: https://curl-online.ching367436.me/?url=example.com%2F
  - name: 'CTF: Curl Online Pro'
    url: https://curl-online-pro.ching367436.me/?url=example.com%2F
  - name: 'CTF: E-Portfolio Baby'
    url: https://e-portfolio-baby.ching367436.me
  - name: 'CTF: E-Portfolio'
    url: https://e-portfolio.ching367436.me
  - name: 'CTF: Flag Checker｜Anti-debugging'
    url: https://flag-checker-anti-debugging.ching367436.me/
  - name: 'CTF: Simple Site'
    url: https://simple-site.ching367436.me
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.ching367436.me
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
